name: Futurerestore

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: Linux Build
        id: Linux
        uses: addnab/docker-run-action@v3
        with:
          image: debian:buster-slim
          options: -v ${{ github.workspace }}/..:/tmp/Builder/repos/
          run: |
            /tmp/Builder/repos/futurerestore/.github/workflows/linux-bootstrap.sh
            /tmp/Builder/repos/futurerestore/.github/workflows/linux-build.sh
            /tmp/Builder/repos/futurerestore/.github/workflows/linux-post.sh
            mkdir -p ${{ github.workspace }}/.github/workflows/
      - name: Linux x86_64 RELEASE Build
        id: Linux-x86_64-RELEASE-Build
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}/../
          mv ${{ github.workspace }}/.github/workflows/futurerestore1.tar.xz ${{ github.workspace }}/.github/workflows/$(cat ${{ github.workspace }}/.github/workflows/name1.txt)
      - name: Linux x86_64 DEBUG Build
        id: Linux-x86_64-DEBUG-Build
        run: |
          mv ${{ github.workspace }}/.github/workflows/futurerestore2.tar.xz ${{ github.workspace }}/.github/workflows/$(cat ${{ github.workspace }}/.github/workflows/name2.txt)
      - name: Linux x86_64 ASAN Build
        id: Linux-x86_64-ASAN-Build
        run: |
          mv ${{ github.workspace }}/.github/workflows/futurerestore3.tar.xz ${{ github.workspace }}/.github/workflows/$(cat ${{ github.workspace }}/.github/workflows/name3.txt)
      - name: futurerestore Linux x86_64 RELEASE Archive
        id: futurerestore-Linux-x86_64-RELEASE-Archive
        uses: actions/upload-artifact@v4
        with:
          name: futurerestore-Linux-x86_64-RELEASE
          path: |
            ${{ github.workspace }}/.github/workflows/futurerestore-Linux-x86_64*-RELEASE.tar.xz
      - name: futurerestore Linux x86_64 DEBUG Archive
        id: futurerestore-Linux-x86_64-DEBUG-Archive
        uses: actions/upload-artifact@v4
        with:
          name: futurerestore-Linux-x86_64-DEBUG
          path: |
            ${{ github.workspace }}/.github/workflows/futurerestore-Linux-x86_64*-DEBUG.tar.xz
      - name: futurerestore Linux x86_64 ASAN Archive
        id: futurerestore-Linux-x86_64-ASAN-Archive
        uses: actions/upload-artifact@v4
        with:
          name: futurerestore-Linux-x86_64-ASAN
          path: |
            ${{ github.workspace }}/.github/workflows/futurerestore-Linux-x86_64*-ASAN.tar.xz
